# Site settings
title: F.R
baseurl: "/fr"
url: "https://FuRuF-11.github.io"
# url: "https://kssim.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Rao Fu
  desc: Hi,nice to meet you
  email: furuf15@gmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: Test
  flickr:
  github: FURUF
  google_plus:
  instagram:
  keybase:
  linkedin:
  # linkedin: https://www.linkedin.com/in/kssim/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: Test
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed


# gems:
  
plugins:
  - jekyll-commonmark-ghpages
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
defaults:
  -
    scope:
      path: ""
    values:
      retry: true
# Gems
# plugins:
  

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
