# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: FR
email: furuf15@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is furao`s personal website.
baseurl: "/FuRuF-11.github.io" # the subpath of your site, e.g. /blog
url: "https://FuRuF-11.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
og_image: /assets/img/profile-pic.jpg
# google_analytics: "UA-121636368-3"
github_username: furuf-11

# Build settings
# theme: minima
# theme: bay_jekyll_theme
header:
  pages:
    - name: Home
      slug: \ 
    - name: Blog
    - name: Work


footer:
  show_powered_by: true
  contact:
    - name: Email
      value: furuf15@gmail.com
      link: mailto:furuf15@gmail.com
    # - name: WeChat
    #   value: YourWeChatUsername
    #   link: "#"
  follow:
    # - name: Twitter
    #   link: http://twitter.com/YourTwitterUsername
    #   username: "@YourTwitterUsername"
    # - name: Facebook
    #   link: http://facebook.com/YourFacebookUsername
    # - name: LinkedIn
    #   link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: https://github.com/FuRuF-11
    # - name: Dribbble
    #   link: https://dribbble.com/YourDribbbleUsername
    # - name: Weibo
    #   link: http://weibo.com/u/YourWeiboUsername
    # - name: RSS
    #   link: /feed.xml


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
